Repository peterprospl12/PotterShop, pull requests merged in 2024-12, with the labels that each got.

#29 API initial version
  .gitignore
  api/README.md
  api/api.py
  api/prestashopAPI.py
  api/product.py
  api/requirements.txt
  api/utils.py
  prestashop/classes/Product.php
Labels: enhancement, api

#33 API Refactor
  api/README.md
  api/api.py
  api/main.py
  api/prestashopAPI.py
  api/product.py
  api/requirements.txt
  api/test_product.py
Labels: documentation, api, tests

#35 Resolved errors in database dump
  data/prestashop.sql
Labels: bug, database

#43 Add databse xdd
  data/prestashop.sql
Labels: database

#45 Redirection fix
  prestashop/themes/child_classic/modules/ps_mainmenu/ps_mainmenu.tpl
Labels: bug, frontend

#47 Tomi product slider
  data/prestashop.sql
  prestashop/override/controllers/front/CartController.php
  prestashop/override/controllers/front/ProductController.php
  prestashop/themes/child_classic/assets/css/custom.css
  prestashop/themes/child_classic/assets/js/custom.js
  prestashop/themes/child_classic/templates/_partials/breadcrumb.tpl
  prestashop/themes/child_classic/templates/catalog/_partials/product-add-to-cart.tpl
  prestashop/themes/child_classic/templates/catalog/product.tpl
  prestashop/themes/classic/templates/catalog/_partials/product-add-to-cart.tpl
  tests/main.py
Labels: bug, frontend

#50 API categories fix
  api/main.py
Labels: bug, api

#49 Ssl configuration
  data/prestashop.sql
  docker-compose.yml
  prestashop/.htaccess
  prestashop/themes/child_classic/modules/ps_mainmenu/ps_mainmenu.tpl
  ssl/000-default.conf
  ssl/Dockerfile
Labels: config, security

#54 README update
  README.md
Labels: documentation

#58 Fix invoices generation
  api/README.md
  api/main.py
  api/prestashopAPI.py
  api/product.py
  api/requirements.txt
  api/test_product.py
  api/utils.py
  data/prestashop.sql
Labels: bug, config

#59 Created size variants for socks and t-shirts; Added 10% discount on o…
  data/prestashop.sql
Labels: config

#61 Fixed smtp credentials
  data/prestashop.sql
Labels: config

#62 Fixed bugs - shirt sizes, footer links redirecting to main page inset…
  data/prestashop.sql
  prestashop/themes/child_classic/assets/css/custom.css
  prestashop/themes/child_classic/templates/catalog/_partials/product-add-to-cart.tpl
  prestashop/themes/child_classic/templates/catalog/_partials/product-flags.tpl
  prestashop/themes/child_classic/templates/catalog/_partials/product-variants.tpl
  prestashop/themes/child_classic/templates/checkout/checkout.tpl
Labels: bug, frontend, database

#63 Bug fix
  data/prestashop.sql
  prestashop/override/controllers/front/ProductController.php
  prestashop/themes/child_classic/assets/css/custom.css
  prestashop/themes/child_classic/assets/js/custom.js
  prestashop/themes/child_classic/templates/catalog/_partials/miniatures/product.tpl
  prestashop/themes/child_classic/templates/catalog/product.tpl
Labels: bug, frontend

#66 menu fix
  data/prestashop.sql
Labels: frontend

#67 Invoices visual fix
  data/prestashop.sql
  prestashop/pdf/header.tpl
  prestashop/pdf/invoice.addresses-tab.tpl
  prestashop/pdf/invoice.tpl
  prestashop/themes/child_classic/modules/ps_shoppingcart/ps_shoppingcart.tpl
  tests/main.py
Labels: bug
