Repository peterprospl12/PotterShop, pull requests merged in 2024-11, with the labels that each got.

#11 Create README.md version 1.0
  README.md
Labels: documentation, enhancement

#5 Adding new workflows
  .github/workflows/check-linked-issue.yml
Labels: enhancement

#22 Revert "Adding new workflows". sory
  .github/workflows/check-linked-issue.yml
Labels: bug
