Repository peterprospl12/PotterShop, pull requests merged in 2025-01, with the labels that each got.

#78 Adding docker pipeline
  .github/workflows/docker-build.yml
Labels: config

#82 Change docker image name
  .github/workflows/docker-build.yml
Labels: bug

#83 Deployment directory update
  deployment/Klaster
  deployment/docker-compose.yml
  deployment/init-db.sh
  deployment/prestashop.sql
  deployment/skrypty_deploymentt
Labels: config

#84 Working tests and custom event in GA
  deployment/prestashop.sql
  prestashop/themes/child_classic/modules/ps_imageslider/views/templates/hook/slider.tpl
  tests/main.py
Labels: bug, tests
